### ISSUE TITLE
Revise discretize.jl

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#117]
After solving #41, we may want to do some refactorings:
* Outsource common parts (e.g., the matrix computation) to helper functions.
* Can we split and determine some functions by types rather than by if-then-else chains?
* ~Outsource the file to a different module? (It is used in `ReachSets` and `Properties`.)~ (outdated)
* Some data is computed several times (e.g., [`exp(δ*Anorm) - 1. - δ*Anorm`](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/discretize.jl#L102)). Avoid this.
* ~Add an option for trying to invert the matrix in the *interpolation* method (instead of the 3n×3n matrix computations).~ see #514

**Comment by mforets** [comment]
- I think that the pull request #503 addresses points 1 and 4. 
- Points 2 is half-addressed since it does not completely remove type checks in the code to handle the inputs, instead of using dispatch -- but i think it is good as is :)
- Point 3 is not addressed, `discretize` still lives in the `ReachSets` module -- i don't have any particular suggestion here. We could move this file upwards to the root `src/discretize.jl`..
- Point 5 is interesting and not addressed in #503; in general one can try to invert the matrix P and obtain Phi1 and Phi2 without exponentiation. I don't have an intuition about the outcome but i propose to make a new issue for experiments.
