### ISSUE TITLE
Reachability of hybrid systems with affine dynamics

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#138]
We have an initial implementation for reachability of a hybrid with affine dynamics [here](https://juliareach.github.io/LazySets.jl/latest/man/reach_zonotopes_hybrid.html).

**Comment by schillic** [comment]
I would suggest to go in stages.

1. Reimplement the LGG algorithm with box directions, i.e., analysis with one big block. Then we see the general problems, and we can suitably compare to SpaceEx.
2. Lift the algorithm to low-dimensional blocks in the most straightforward way. Then we see the problems with that.
3. Implement heuristics to make 2. efficient.

Note that safety property checking can be reduced to hybrid reachability by adding a transition from each location to an error location, with the guard being the negated safety property.

A typical hybrid reachability algorithm works as follows:
1. Split the initial states into pairs `(loc, X0)` of location `loc` and state region `X0`. Add them to a queue of triples `(loc, X0, T*)`, where `T*` is the time horizon.
2. Terminate if the queue is empty. Otherwise pick and remove one element `(loc, X0, T)` from the queue.
3. Compute the (continuous) reach set (a flowpipe) from initial region `X0` over the time horizon `T` according to `loc`'s dynamics. The reach set is a sequence of sets `X(k)`, `k >= 0`.
4. Intersect each set in the flowpipe with the invariant `I` of `loc` and each of the guards `G` from location `loc` (i.e., compute `R = X(k) ∩ I` and then `S = R ∩ G`). Whenever the intersection `S` is nonempty, compute the successor by applying the assignment `A` of the transition and intersect with the invariant `I'` of the target location `loc'`: `Y = A(S) ∩ I'`. Add the triple `(Y, loc', T-t)` to the queue, where `t` is the time that was consumed in `loc` (i.e., `(k-1) * δ`).
5. Go to 2.

Remarks:
1. `t = (k-1) * δ` has nontermination issues if `k = 1`. What do other tools do here?
2. For our low-dimensional algorithm to be efficient, we probably want to only compute those dimensions that the guards talk about.
3. Observe that `X0` in the queue triples needs to be a full-dimensional reach set. Thus we need `Y` to be full-dimensional as well. For our low-dimensional algorithm to be efficient, we probably want to compute `X(k)` only if the jump has to be taken (i.e., lazily).

**Comment by schillic** [comment]
There are good explanations and illustrations of a basic algorithm in [this paper](http://www.i6.in.tum.de/Main/Publications/Althoff2009b.pdf) by M. Althoff et al.
They additionally care for conversion between zonotopes and polytopes, but for a start we can ignore that.

**Comment by schillic** [comment]
I'll close this one. We have added basic support for hybrid systems a while ago and the other suggestions are being worked on.
