### ISSUE TITLE
Decomposition became much slower for lazy_expm mode

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#147]
Recent changes made decomposition for MNA5 run much slower. I ran it for at least 30 minutes and finally stopped it.
On March 27, 10 am, the whole analysis (which decomposition is only a part of) took 970 seconds (1D `Interval`) resp. 1,568 seconds (2D `Hyperrectangle`).

**Comment by schillic** [comment]
I narrowed it down to this:
`LazySets.jl`: [`976ff4b`](https://github.com/JuliaReach/LazySets.jl/commit/976ff4b19c902545542366c5bef4ab2d260651e9) still works, [`6bfd431`](https://github.com/JuliaReach/LazySets.jl/commit/6bfd431e0695f02ca77b38d0abde63c1faa25508) does not work anymore
For `Reachability.jl` one can use e8420e9.
The effect is less visible for the FOM model with `lazy_expm` option:
```
[info] - Decomposing X0
[info] elapsed time: 1.679548582 seconds

# vs.

[info] - Decomposing X0
[info] elapsed time: 2.407215414 seconds
```

**Comment by mforets** [comment]
Here it works:

```julia
compute(:δ => 1e-3, :N => 3, :mode=>"reach", :verbosity => "info", :lazy_expm=>true, :set_type=>Interval, :partition => [[i] for i in 1:10913])
[info] Time discretization...
[info] elapsed time: 342.700746425 seconds
[info] Reachable States Computation...
[info] - Decomposing X0
[info] elapsed time: 707.852182514 seconds
[info] - Computing successors
[info] elapsed time: 2.667469983 seconds
[info] - Total
[info] elapsed time: 712.20336396 seconds
[info] Projection...
[info] elapsed time: 0.360965227 seconds
```

For the real `compute(:δ => 1e-3, :T => 20.0, :mode=>"reach", :verbosity => "info", :lazy_expm=>true, :set_type=>Interval, :partition => [[i] for i in 1:10913])` the cost of discretization and decomposition is the same, no?

The changeset [#304](https://github.com/JuliaReach/LazySets.jl/pull/304) cannot affect decomposition i think because decomposition uses calls to the support vector `\sigma` directly, first through the generic [project](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Approximations/decompositions.jl#L260), then through [overapproximate](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Approximations/overapproximate.jl#L122) for intervals. OTOH, the functions `get_row(s)` and `get_column(s)`for a `SparseMatrixExp` are used only in the computation of succesors, in [reach_blocks](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/reach_blocks.jl#L210).
 

(To evaluate the support vector in some direction of a runtime object i used a call like `save("X0_mna5.jld", "X0")` inside from [JLD](https://github.com/JuliaIO/JLD.jl): in `reach`. It can be loaded in another session like:

```julia
using JLD
julia> X0 = load("X0_mna5.jld", "X0");
julia> v = sparsevec([10], [1.0], 10913);
julia> @time σ(v, X0);
  0.015218 seconds (306 allocations: 7.295 MiB)
```
For this model it takes around `150ms... 200ms`.

**Comment by schillic** [comment]
I just double-checked the experiment with FOM. Interestingly, the difference is only visible for `Hyperrectangle` decomposition. For `HPolygon` with box directions the runtime is the same.

For MNA5 it is so much slower. I added a `ProgressMeter` to the decomposition and it estimates the runtime at ~35 minutes (with the older revision it says ~9 minutes).

I agree that the PR should **not** have any effect on the decomposition. What is going on here?

**Comment by schillic** [comment]
I found out why we use `get_columns` during decomposition:
The discretization by default uses a lazy symmetric interval hull.
Thus when we evaluate the support vector in the decomposition, we actually perform the lazy compuation and call `get_columns`.
