### ISSUE TITLE
Check of time horizon might  be wrong

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/Reachability.jl#339]
Here is result for filtered oscillator in SpaceEx with `T=2`
<img width="685" alt="screen shot 2018-10-16 at 3 39 14 pm" src="https://user-images.githubusercontent.com/7996008/46993186-aa0be180-d159-11e8-9f65-a5df22a7fb4c.png">
Here is results in JuliaReach:
<img width="497" alt="screen shot 2018-10-16 at 3 40 50 pm" src="https://user-images.githubusercontent.com/7996008/46993238-dfb0ca80-d159-11e8-8445-c22be952a4b8.png">

**Comment by schillic** [comment]
The uncertain time interval of our last set is `[1.99, 2.7]` for a time step of `0.01`. From the SpaceEx plot it looks correct that the transition cannot be taken yet.
Since I think that the timing information is tracked correctly, and assuming that our continuous post operation returns the correct number of steps, I rather suspect that SpaceEx is overly conservative here.

**Comment by schillic** [comment]
The SpaceEx model is different from ours, so we cannot compare.
