### ISSUE TITLE
Preprocess HS to get only necessary variables

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/Reachability.jl#397]
We want to operate only with variables, which are used in guard and invariant constraints.

For discussion:
Do we need to add variables, the value of which in LinearTransformation is not 1?

**Comment by kostakoida** [comment]
@mforets no, I mean if we have `ResetMap` in the transition, which is not a `IdentityMap`, should we process it too?

**Comment by schillic** [comment]
If we want to support #269, this is a different story, but for the "pure" #275, we do not have to consider assignments (because they are applied after the jump).

Let me add that we actually want to detect these "necessary" variables per location, not globally. In practice that may often be the same, but the idea is more general.
So for each location we want to scan the invariant and all *outgoing* transitions.

**Comment by mforets** [comment]
> So for each location we want to scan the invariant and all outgoing transitions.

Note: the output of the initial implementation (in https://github.com/JuliaReach/Reachability.jl/pull/398) does not distinguish if the variables come from the invariant or from transitions.
