### ISSUE TITLE
Support for reset assignments

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#441]
A special case of #273.

Two options:
1) project reset dimensions to zero and add a singleton corresponding to the reset via Minkowski sum
2) fully project reset dimensions away and take the Cartesian product with (generally several) singletons corresponding to the reset

Example: 2D, we want to reset the first variable to 3.
1) `\begin{pmatrix} 0 0 \\ 0 1 \end{pmatrix}x + \{\binom{3}{0}\}`
2) `\{(3)\} \times \begin{pmatrix} 0 1 \end{pmatrix}x`

Option 1) seems easier to implement because it does not care about the position of the resets.
Option 2) could be interesting if the projection is easy to obtain because the set is already Cartesian (e.g., a `CartesianProductArray` from the low-dimensional continuous-time reachability or a `Hyperrectangle` from a box approximation).

**Comment by mforets** [comment]
The reset map was added in [MathematicalSystems#55](https://github.com/JuliaReach/MathematicalSystems.jl/pull/55). Perhaps we need a new function to transform it  to matrix form. Because its [apply function](https://github.com/JuliaReach/MathematicalSystems.jl/pull/57/files#diff-284dc116141fb7d4245f2213e5142052R193) does not apply 😄  to sets, since it assumes that `x` is a vector in `y[index] = value`... we may extend `apply(m::ResetMap, x::LazySet)` with the projection as you propose above.
