### ISSUE TITLE
Accept non-hyperrectangular sets for the discretization with zonotopes

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#530]
In https://github.com/JuliaReach/Reachability.jl/pull/528 we added the option `set_operations` with default value `"lazy"`. If `set_operations` is `"zonotope"`, it uses concrete operations between zonotopes, and needs to convert to zonotope. Sets such as `Ball2` is not allowed.

Proposal: if `convert(Zonotope, X0)` is not available, call `overapproximate(X0, Zonotope)` or (if it is not defined), just `convert(Zonotope, overapproximate(X0, Hyperrectangle))`.

**Comment by schillic** [comment]
I changed my mind here.
It does not make sense to use zonotopes if the sets in the input are not given as zonotopic sets. Since there is (probably) no generic overapproximation method for zonotopes, unexpected things can happen.
I would say that the user should take care of the conversion in advance. Hence I would say that we can keep the existing `convert`s.

**Comment by mforets** [comment]
Alright, agreed.
