### ISSUE TITLE
Add verbosity level option and deactivate some outputs by default

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#7]
- make the printing of the timings optional
- verbosity level

to begin with, we can add a verbose true/false mode to the `solve` interface.

(cf. gl iss 124)

**Comment by schillic** [comment]
My plan is having a `verbosity` option with integer values on the interface level (e.g., 0 to 3).

Internally we can use strings (or `Symbol`s?) for better control.
Then we have a logger type, which is just a mapping from strings to log levels, and a guarded print function `log(log_level, level, message)` which ignores the message if the log level is deactivated and otherwise prints it.
Example: `log(log_level, "debug", "my debug message")`

We can later add a function `log_active(level)` that returns `false` if the given log level is deactivated in case we want add expensive outputs.

We should have a global variable for the log level; then we do not have to pass around this logger all the time, which is probably a mess.
Example: `log("debug", "my debug message")`

Julia supports three basic output streams: [info](https://docs.julialang.org/en/stable/stdlib/io-network/#Base.info), [warn](https://docs.julialang.org/en/stable/stdlib/io-network/#Base.warn), [error](https://docs.julialang.org/en/stable/stdlib/base/#Base.error). They can be uniformly handled with the [logging](https://docs.julialang.org/en/stable/stdlib/io-network/#Base.logging) function.
Maybe we also want that?
We can even define individual message headers such as `INFO`.

**Comment by mforets** [comment]
interesting, do you have some applications/examples of `logging`? what is "divert stream for a module"? 

atm, as i said in the chat i don't see that an infrastructure of different levels of verbosity is justified, given the interactive nature of the REPL.. maybe becomes more crucial if in the future we [distribute a statically compiled version, with this project](https://github.com/JuliaComputing/static-julia).

**Comment by schillic** [comment]
Agreed, I will think about an interface that can be extended later but is lightweight for the moment.

**Comment by schillic** [comment]
We now have the function `info(msg)` which is controlled by the option `:verbosity`.
Note that the actual guard is a global variable `G_LOG`, i.e., when the program terminates in the REPL, this variable still retains its old value.
This also means that alternatively you can just write this variable in the REPL initially.

I had to create a new function `tocc()` to be used instead of `toc()`.

By default the logging is deactivated. Should we activate it by default?

(The last commit is unrelated, I just stumbled upon it.)

**Comment by mforets** [comment]
Okay, i've tested it, great 👍   

since it is a true/false option, i'd rather name it `verbose`, but this is just a side comment. 

i started to read the links you provided in the earlier comment, here are some more (only for future reference):

- https://discourse.julialang.org/t/best-practice-for-functions-which-print-debugging-info/1522
- https://github.com/kmsquire/Logging.jl
- https://invenia.github.io/Memento.jl/latest/faq/another-logging-lib.html

> We now have the function info(msg)..

should the `info` function be inlined?

> I had to create a new function tocc() to be used instead of toc().

is the built-in function `toq()` helpful in that respect? otherwise the macro `@elapsed`? 

> By default the logging is deactivated. Should we activate it by default?

i think it should *not* be active by default.

**Comment by mforets** [comment]
don't forget to make the PR

**Comment by schillic** [comment]
`Memento.jl` looks very mature, I want to try out that one.
The downside is that you have to create a logger object and always pass it to the log function.
This is the right way to do it, but it is a bit annoying.
I also do not know if we need the ability to create loggers for each module.
This might be interesting for library code, but here we are the end user I guess.
Maybe we can create a global logger and make it the default argument as a shortcut 😑

The problem with `toc()` is that I cannot import a `Base` function and call it again conditionally.
It will be overwritten by the new function and then you have an infinite loop (I tried it 😉).

**Comment by schillic** [comment]
I tried the `Memento.jl` package and like it.

We now allow the option `:verbosity` with either a value in `{0, 1, 2}` or a string from [this table](https://invenia.github.io/Memento.jl/latest/man/intro.html#Logging-levels-1).
The integer values denote logging for warning level or worse (0, default), info level or worse (1), and debug level (the lowest level) (2). For an invalid integer we print a nice error message.
For an invalid string there is unfortunately a strange error that is thrown by the package.
We could test the strings first and print a better message, but I do not expect a user to try with the string values anyway.

The `toc()` function is a bit nasty. As before we have the function `tocc()` for printing on the info level.
If we want to print on, e.g., debug level, we need to add a function for that (or better: add an optional argument to `tocc`).

@mforets: If you accept this solution, I will need to do some things before adding the PR:
* provide functions for `warn` and `debug` (more?)
* add `@inline` to the log functions
* add documentation

**Comment by mforets** [comment]
cool, thanks for investing on this!

> The toc() function is a bit nasty.

have you checked out their "syntactic sugar"  package [Trace](https://invenia.github.io/Trace.jl/latest/index.html)?

seems like [@trace](https://github.com/invenia/Trace.jl/blob/9b1b2b10f51782a75e8ca4a521ae1bd6040694c2/src/macros.jl#LL35-L40) is what we need.

**Comment by schillic** [comment]
> have you checked out their "syntactic sugar" package Trace?
seems like @trace is what we need.

This is a cool thing to remember if we have expensive outputs that should not be computed if printing is disabled.
But I do not see the connection to `toc`.

The problem with `toc` is that it prints on the standard output stream, i.e., it does not use the logging function. My `tocc` function does exactly this.
