### ISSUE TITLE
Inconsistent behavior for assume_sparse mode

### ISSUE THREAD

**Issue by schillic** [JuliaReach/Reachability.jl#94]
Compare [this block in reach](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/reach.jl#L70) with [this block in check_property](https://github.com/JuliaReach/Reachability.jl/blob/master/src/Properties/check_property.jl#L66).

The further crashes for the MNA5 model.

Which one should we use?

**Comment by mforets** [comment]
The original idea of these `if assume_sparse` blocks was to ensure that: if `assume_sparse` is `true`, then dispatch the specialization which receives a sparse matrix as input (in principle, no matter if you give me a dense or a sparse `A`, so in some cases i must do the conversion).

This turned out to be convenient for the tests, since we could play around with the same model definition but changing just a `true/false` flag.

How about:

```julia
    #coefficients matrix
    if assume_sparse
        try
            push!(args, sparse(S.A))
        catch
             push!(args, S.A)
        end
    else
        try
            push!(args, full(S.A))
        catch
            push!(args, S.A)
        end
end
```

**Comment by schillic** [comment]
Should we then do this conversion already one level higher (in `solve`)?
I prefer this over duplicated code.
We could have a `preprocess` function in `solve` which does these things.

**Comment by mforets** [comment]
Okay, why not. But we shouldn't forget that sparse/nonsparse is particular of this method of solution and this system. Later on we would like that `solve(system::AbstractSystem, options_input::Options)` provides different solutions methods on different systems, and they do their job. In other words, keeping `solve` simple is a good thing IMO.

**Comment by schillic** [comment]
I would argue that `solve` is already very tied to these methods.
